services:
  rust-backend:
    build:
      context: ./rust-backend
    container_name: rust-backend
    expose:
      - "8000"
    environment:
      - HTTP_PORT=8000
      - CONFIG_DIR=/app/config
      - LAYER_DIR=/app/layers
      - LOG_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./layers:/app/layers
    restart: unless-stopped

  node-backend:
    build:
      context: ./node-backend
    container_name: node-backend
    ports:
      - "3000:3000"
    environment:
      - HTTP_ADDRESS=0.0.0.0
      - HTTP_PORT=3000
      - HTTP_HOST=https://beacon-ihm.maris.nl
      - RUST_BACKEND_URL=http://rust-backend:8000
      - CONFIG_DIR=/app/config
      - LOG_DIR=/app/logs
      - PATH_PREFIX=/wms
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - rust-backend
    restart: unless-stopped
